version: '3.8'

services:
  bot:
    build: .
    restart: unless-stopped
    ports:
      - "8170:8170"
    volumes:
      - ./data:/app/data
    env_file:
      - .env.test

networks:
  sensitive-lexicon:
    driver: bridge

