name: CI

on:
  push:
    branches:
      - master

jobs:
  check:
    name: Syntax Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Check syntax
        run: python -m py_compile src/nonebot_plugin_sensitive_lexicon/*.py
